"""Baseline training: fit, evaluate, and refuse to do either through a leak.

Runs both model variants against all three splits, so the spike's comparison
table is regenerated by a command rather than quoted from a document. The
temporal number is the headline; the other two are printed beside it to show
how much more flattering they are.

The leakage validator runs again here, after splitting, because splitting
introduces a failure the feature stage cannot see: the same row, or the same
player, landing on both sides of the boundary.
"""

from __future__ import annotations

from dataclasses import dataclass

import pandas as pd
from sklearn.pipeline import Pipeline

from src.evaluation.metrics import Metrics, evaluate
from src.feature_engineering.build import (
    CATEGORICAL_FEATURES,
    TARGET_COLUMN,
    select_variant,
)
from src.models.baseline import BASELINE_MODELS
from src.models.splits import RANDOM_SEED, Split, group_split, random_split, temporal_split
from src.pipelines.features import TRAINING_TABLE, leakage_validator
from src.storage.base import TableStore
from src.utils.config import SplitConfig
from src.utils.logging import get_logger

logger = get_logger(__name__)

VARIANTS = {"performance_only": False, "with_prior_value": True}
"""The two models the data forces this project to ship (00-discovery.md 2.3).
Publishing only the accurate one would be technically true and useless."""


@dataclass(frozen=True)
class BaselineResult:
    """One model, one variant, one split."""

    variant: str
    split: str
    model: str
    validation: Metrics
    test: Metrics

    @property
    def is_headline(self) -> bool:
        """Only the temporal split reflects deployment."""
        return self.split == "temporal"


def build_splits(frame: pd.DataFrame, config: SplitConfig) -> list[Split]:
    """The temporal split first, because it is the one that counts."""
    return [
        temporal_split(
            frame,
            train_end_season=config.train_end_season,
            validation_season=config.validation_season,
            test_start_season=config.test_start_season,
        ),
        group_split(frame, seed=RANDOM_SEED),
        random_split(frame, seed=RANDOM_SEED),
    ]


def fit_and_score(
    model: Pipeline,
    frame: pd.DataFrame,
    split: Split,
    feature_columns: tuple[str, ...],
) -> tuple[Metrics, Metrics]:
    """Fit on train, score on validation and test. Both in EUR."""
    features = list(feature_columns)
    train = frame.loc[split.train]
    model.fit(train[features], train[TARGET_COLUMN])

    scores = []
    for rows in (frame.loc[split.validation], frame.loc[split.test]):
        scores.append(evaluate(rows[TARGET_COLUMN], model.predict(rows[features])))
    return scores[0], scores[1]


def run_baselines(store: TableStore, config: SplitConfig) -> list[BaselineResult]:
    """Every variant against every split, with leakage re-checked after each split.

    Raises:
        ValidationError: if any split leaks. Metrics are not produced from a
            leaking split — a number that looks good for the wrong reason is
            worse than no number, because it gets believed.
    """
    table = store.read_table(TRAINING_TABLE)
    results: list[BaselineResult] = []

    for variant, include_prior in VARIANTS.items():
        frame, feature_columns = select_variant(table, include_prior_value=include_prior)
        validator = leakage_validator(feature_columns)

        for split in build_splits(frame, config):
            # The check the feature stage could not run: splitting is what
            # creates the chance of a row or a player straddling the boundary.
            report = validator.validate(frame, splits=split.as_dict(), groups=frame["player_id"])
            report.raise_for_errors()

            for name, factory in BASELINE_MODELS.items():
                numeric = [c for c in feature_columns if c not in CATEGORICAL_FEATURES]
                validation, test = fit_and_score(
                    factory(numeric, CATEGORICAL_FEATURES), frame, split, feature_columns
                )
                results.append(BaselineResult(variant, split.name, name, validation, test))
                logger.info("%s / %s / %s -> test %s", variant, split.name, name, test.render())

    return results


def render_comparison(results: list[BaselineResult]) -> str:
    """The spike's table, regenerated.

    Temporal is marked because it is the number to quote. A random-split R^2 on
    a time series answers a question nobody deploying this will ever ask.
    """
    header = f"{'variant':<18} {'split':<10} {'model':<18} " f"{'test MAE EUR':>14} {'test R2':>9}"
    lines = [header, "-" * len(header)]

    for result in results:
        marker = " *" if result.is_headline else "  "
        lines.append(
            f"{result.variant:<18} {result.split:<10} {result.model:<18} "
            f"{result.test.mae:>14,.0f} {result.test.r2:>9.3f}{marker}"
        )

    lines.append("")
    lines.append("* temporal split — the reported headline. Random and group splits")
    lines.append("  flatter the model by letting it see seasons it will not see in use.")
    return "\n".join(lines)
